version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi_app
    command: ["uvicorn", "main:app", "--host", "localhost", "--port", "8000"]
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/chat
    depends_on:
      - db
      - redis
      - celery_worker

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app

  db:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: chat
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: redis

  celery_worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: celery_worker
    command: ["celery", "-A", "celery_app", "worker", "--loglevel=info", "--pool=solo"]
    depends_on:
      - redis
      - db

volumes:
  postgres_data:
